import Arriba from "./_Arriba/Arriba";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <div>
      <div>
        <Arriba></Arriba>
      </div>
      <div>{children}</div>
    </div>
  );
}
