import "./globals.css";
import { Inter } from "next/font/google";
import Script from "next/script";
import Abajo from "./_layout_abajo/abajo";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Script
        type="module"
        src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"
      ></Script>
      <Script
        nomodule
        src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"
      ></Script>
      <body className={inter.className}>
        <div>
          <div>{children}</div>
          <div>
            <Abajo></Abajo>
          </div>
        </div>
      </body>
    </html>
  );
}
